baseURL = 'https://NoneNews.github.io/'
languageCode = 'zh-cn'
title = 'Nonebot阳间新闻网站'
theme = "spectre-pixel"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  name = "NoneNews"                     # 你的名字
  altName = "牛牛"                      # 简写
  description = "Nonebot阳间新闻网站" # 你的网站描述
  bio = "Nonebot怎么能少了阴间新闻"
  enableRSS = true                      # 是否启用RSS(订阅相关)

  # 作者信息
  aboutAuthor = "Nonebot阳间新闻网站"

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  # 客制化CSS和JS文件
  customCSS = [
    "https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css"
  ]
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
	home = ""
	subscribe = ""

	# Pagination links
	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

# Add additional social link entries underneath
  [Social]
    email    = "None"
    facebook = "https://www.facebook.com/"
    github   = "https://www.github.com/"
    linkedin = "https://www.linkedin.com/"
    twitter  = "https://www.twitter.com/"

[taxonomies]
  tag = "tags"
